/** Homely Pets — catalog organised by pet + life stage / product type */

window.HOMELY_PRODUCTS = [
  /* ═══════════════════ DOGS ═══════════════════ */

  /* —— Puppy food —— */
  {
    id: "dog-puppy-dry-salmon",
    name: "Puppy Dry — Salmon & Potato (2kg)",
    pet: "dog",
    segment: "puppy",
    type: "Dry food",
    size: "2kg",
    price: 27.9,
    badge: "Bestseller",
    img: "homely-pets-dry-food-bag.png",
    desc: "DHA and smaller kibble for brain development and growing jaws up to 12 months.",
  },
  {
    id: "dog-puppy-dry-chicken",
    name: "Puppy Dry — Chicken & Rice (2kg)",
    pet: "dog",
    segment: "puppy",
    type: "Dry food",
    size: "2kg",
    price: 26.5,
    img: "homely-pets-dry-food-bag.png",
    desc: "High calcium and controlled phosphorus for steady bone growth.",
  },
  {
    id: "dog-puppy-wet-pate",
    name: "Puppy Wet — Chicken Paté (10 pack)",
    pet: "dog",
    segment: "puppy",
    type: "Wet food",
    size: "10 × 85g",
    price: 15.9,
    img: "homely-pets-wet-food-packaging.png",
    desc: "Soft paté for weaning and young pups. Easy to digest.",
  },
  {
    id: "dog-puppy-wet-beef",
    name: "Puppy Wet — Beef & Carrot Stew (8 pack)",
    pet: "dog",
    segment: "puppy",
    type: "Wet food",
    size: "8 × 150g",
    price: 17.5,
    img: "homely-pets-wet-food-packaging.png",
    desc: "Hearty stew trays with extra calories for fast-growing breeds.",
  },

  /* —— Adult food —— */
  {
    id: "dog-adult-dry-chicken-2",
    name: "Adult Dry — Chicken & Sweet Potato (2kg)",
    pet: "dog",
    segment: "adult",
    type: "Dry food",
    size: "2kg",
    price: 24.9,
    badge: "Bestseller",
    img: "homely-pets-dry-food-bag.png",
    desc: "Complete grain-free kibble. Single-source chicken for digestion and coat health.",
  },
  {
    id: "dog-adult-dry-chicken-6",
    name: "Adult Dry — Chicken & Sweet Potato (6kg)",
    pet: "dog",
    segment: "adult",
    type: "Dry food",
    size: "6kg",
    price: 54.9,
    badge: "Value size",
    img: "homely-pets-dry-food-bag.png",
    desc: "Same trusted adult recipe — better per-bowl value for multi-dog homes.",
  },
  {
    id: "dog-adult-dry-lamb",
    name: "Adult Dry — Lamb & Brown Rice (2kg)",
    pet: "dog",
    segment: "adult",
    type: "Dry food",
    size: "2kg",
    price: 26.5,
    img: "homely-pets-dry-food-bag.png",
    desc: "Gentle on sensitive stomachs. Lamb first with omega-rich oils.",
  },
  {
    id: "dog-adult-dry-beef",
    name: "Adult Dry — Beef & Barley (2kg)",
    pet: "dog",
    segment: "adult",
    type: "Dry food",
    size: "2kg",
    price: 25.5,
    img: "homely-pets-dry-food-bag.png",
    desc: "Hearty beef protein with barley for steady daily energy.",
  },
  {
    id: "dog-adult-dry-duck",
    name: "Adult Dry — Grain-Free Duck & Parsnip (2kg)",
    pet: "dog",
    segment: "adult",
    type: "Dry food",
    size: "2kg",
    price: 31.9,
    img: "homely-pets-dry-food-bag.png",
    desc: "Novel protein for dogs with chicken sensitivities.",
  },
  {
    id: "dog-adult-dry-large",
    name: "Adult Dry — Large Breed Turkey & Oats (3kg)",
    pet: "dog",
    segment: "adult",
    type: "Dry food",
    size: "3kg",
    price: 29.9,
    img: "homely-pets-dry-food-bag.png",
    desc: "Controlled calories and glucosamine for bigger adult dogs.",
  },
  {
    id: "dog-adult-dry-small",
    name: "Adult Dry — Small Breed Chicken & Quinoa (1.5kg)",
    pet: "dog",
    segment: "adult",
    type: "Dry food",
    size: "1.5kg",
    price: 22.9,
    img: "homely-pets-dry-food-bag.png",
    desc: "Smaller kibble and higher calorie density for dogs under 10kg.",
  },
  {
    id: "dog-adult-wet-salmon",
    name: "Adult Wet — Salmon & Pea (12 pack)",
    pet: "dog",
    segment: "adult",
    type: "Wet food",
    size: "12 × 85g",
    price: 18.5,
    img: "homely-pets-wet-food-packaging.png",
    desc: "High-moisture trays for picky eaters or mixed feeding.",
  },
  {
    id: "dog-adult-wet-turkey",
    name: "Adult Wet — Turkey & Cranberry (12 pack)",
    pet: "dog",
    segment: "adult",
    type: "Wet food",
    size: "12 × 85g",
    price: 17.9,
    img: "homely-pets-wet-food-packaging.png",
    desc: "Smooth paté texture. Ideal flavour rotation for adult dogs.",
  },
  {
    id: "dog-adult-wet-beef",
    name: "Adult Wet — Beef Stew Trays (7 pack)",
    pet: "dog",
    segment: "adult",
    type: "Wet food",
    size: "7 × 150g",
    price: 16.5,
    img: "homely-pets-wet-food-packaging.png",
    desc: "Chunky gravy stew — perfect as a kibble topper.",
  },
  {
    id: "dog-adult-wet-lamb",
    name: "Adult Wet — Lamb & Rosemary (12 pack)",
    pet: "dog",
    segment: "adult",
    type: "Wet food",
    size: "12 × 85g",
    price: 18.9,
    img: "homely-pets-wet-food-packaging.png",
    desc: "Rich lamb paté with rosemary for sensitive adult dogs.",
  },

  /* —— Senior food —— */
  {
    id: "dog-senior-dry-joint",
    name: "Senior Dry — Turkey & Joint Care (2kg)",
    pet: "dog",
    segment: "senior",
    type: "Dry food",
    size: "2kg",
    price: 28.5,
    img: "homely-pets-dry-food-bag.png",
    desc: "Lower fat with green-lipped mussel and turmeric for dogs 7+ years.",
  },
  {
    id: "dog-senior-dry-light",
    name: "Senior Dry — Light Turkey & Pumpkin (2kg)",
    pet: "dog",
    segment: "senior",
    type: "Dry food",
    size: "2kg",
    price: 27.5,
    img: "homely-pets-dry-food-bag.png",
    desc: "Reduced calories for less active seniors while maintaining muscle mass.",
  },
  {
    id: "dog-senior-wet-turkey",
    name: "Senior Wet — Turkey & Rice (12 pack)",
    pet: "dog",
    segment: "senior",
    type: "Wet food",
    size: "12 × 85g",
    price: 17.5,
    img: "homely-pets-wet-food-packaging.png",
    desc: "Soft texture with joint-support nutrients for mature dogs.",
  },
  {
    id: "dog-senior-wet-fish",
    name: "Senior Wet — White Fish & Sweet Potato (12 pack)",
    pet: "dog",
    segment: "senior",
    type: "Wet food",
    size: "12 × 85g",
    price: 18.9,
    img: "homely-pets-wet-food-packaging.png",
    desc: "Light, digestible fish recipe for seniors with sensitive digestion.",
  },

  /* —— Competition & bulking —— */
  {
    id: "dog-comp-dry-bulk",
    name: "Competition Dry — High-Calorie Bulk (4kg)",
    pet: "dog",
    segment: "competition",
    type: "Dry food",
    size: "4kg",
    price: 44.9,
    badge: "Performance",
    img: "homely-pets-dry-food-bag.png",
    desc: "520 kcal/cup formula for muscle gain, show dogs, and working breeds in heavy training.",
  },
  {
    id: "dog-comp-dry-power",
    name: "Competition Dry — Power Protein 38% (3kg)",
    pet: "dog",
    segment: "competition",
    type: "Dry food",
    size: "3kg",
    price: 39.9,
    img: "homely-pets-dry-food-bag.png",
    desc: "Very high animal protein with added creatine support for competition conditioning.",
  },
  {
    id: "dog-comp-wet-recovery",
    name: "Competition Wet — Post-Workout Recovery (12 pack)",
    pet: "dog",
    segment: "competition",
    type: "Wet food",
    size: "12 × 150g",
    price: 24.5,
    img: "homely-pets-wet-food-packaging.png",
    desc: "Electrolytes, BCAAs, and high protein for dogs after intense training or trials.",
  },
  {
    id: "dog-comp-wet-mass",
    name: "Competition Wet — Muscle Mass Booster (8 pack)",
    pet: "dog",
    segment: "competition",
    type: "Wet food",
    size: "8 × 200g",
    price: 22.9,
    img: "homely-pets-wet-food-packaging.png",
    desc: "Calorie-dense gravy trays to add lean mass between show or sport seasons.",
  },
  {
    id: "dog-comp-supp-gainer",
    name: "Competition Supplement — Calorie Gainer Powder",
    pet: "dog",
    segment: "competition",
    type: "Supplement",
    size: "500g",
    price: 26.9,
    img: "homely-pets-packaging-mailer.png",
    desc: "Mix into wet or dry food for competition dogs needing extra daily calories.",
  },
  {
    id: "dog-comp-supp-protein",
    name: "Competition Supplement — Whey Protein Topper",
    pet: "dog",
    segment: "competition",
    type: "Supplement",
    size: "400g",
    price: 29.5,
    img: "homely-pets-packaging-mailer.png",
    desc: "Palatable protein powder for bulking phases. Vet-advised for sport dogs only.",
  },

  /* —— Dog snacks & treats —— */
  {
    id: "dog-snack-training",
    name: "Training Bites — Chicken",
    pet: "dog",
    segment: "snacks",
    type: "Snacks",
    size: "200g",
    price: 6.5,
    img: "homely-pets-packaging-mailer.png",
    desc: "Low-calorie rewards for recall and obedience training.",
  },
  {
    id: "dog-snack-jerky",
    name: "Air-Dried Beef Jerky Strips",
    pet: "dog",
    segment: "snacks",
    type: "Snacks",
    size: "120g",
    price: 9.5,
    img: "homely-pets-packaging-mailer.png",
    desc: "Single-protein strips. High-value reward for sport and show dogs.",
  },
  {
    id: "dog-snack-dental",
    name: "Dental Sticks — Mint & Parsley",
    pet: "dog",
    segment: "snacks",
    type: "Snacks",
    size: "14 sticks",
    price: 8.9,
    img: "homely-pets-packaging-mailer.png",
    desc: "Daily chew that helps reduce plaque between brushings.",
  },
  {
    id: "dog-snack-puppy-biscuit",
    name: "Puppy Biscuits — Oat & Carrot",
    pet: "dog",
    segment: "snacks",
    type: "Snacks",
    size: "300g",
    price: 7.5,
    img: "homely-pets-packaging-mailer.png",
    desc: "Gentle baked biscuits with calcium for growing teeth.",
  },
  {
    id: "dog-snack-lick",
    name: "Lickable Purée — Peanut & Banana (6 pack)",
    pet: "dog",
    segment: "snacks",
    type: "Snacks",
    size: "6 × 90g",
    price: 8.9,
    img: "homely-pets-wet-food-packaging.png",
    desc: "Spread on mats for calm enrichment. No xylitol.",
  },
  {
    id: "dog-snack-salmon",
    name: "Freeze-Dried Salmon Cubes",
    pet: "dog",
    segment: "snacks",
    type: "Snacks",
    size: "50g",
    price: 7.9,
    img: "homely-pets-packaging-mailer.png",
    desc: "Single-ingredient omega-rich snack. Break into smaller pieces.",
  },

  /* —— Dog chew toys —— */
  {
    id: "dog-chew-rubber",
    name: "Natural Rubber Chew Ring",
    pet: "dog",
    segment: "chews",
    type: "Chew toy",
    size: "Large",
    price: 12.5,
    badge: "Bestseller",
    img: "homely-pets-packaging-mailer.png",
    desc: "Durable rubber ring for power chewers. Dishwasher safe.",
  },
  {
    id: "dog-chew-rope",
    name: "Cotton Rope Tug — Medium",
    pet: "dog",
    segment: "chews",
    type: "Chew toy",
    size: "32cm",
    price: 11.9,
    img: "homely-pets-packaging-mailer.png",
    desc: "Natural cotton rope for interactive tug and gentle flossing.",
  },
  {
    id: "dog-chew-antler",
    name: "Split Elk Antler Chew",
    pet: "dog",
    segment: "chews",
    type: "Chew toy",
    size: "Medium",
    price: 18.9,
    img: "homely-pets-packaging-mailer.png",
    desc: "Long-lasting natural chew. Low odour, rich in minerals.",
  },
  {
    id: "dog-chew-bully",
    name: "Odour-Reduced Bully Sticks (6 pack)",
    pet: "dog",
    segment: "chews",
    type: "Chew toy",
    size: "6 sticks",
    price: 14.5,
    img: "homely-pets-packaging-mailer.png",
    desc: "High-protein long chew for anxious dogs and crate time.",
  },
  {
    id: "dog-chew-dental-bone",
    name: "Enriched Dental Chew Bone — Large",
    pet: "dog",
    segment: "chews",
    type: "Chew toy",
    size: "1 bone",
    price: 5.5,
    img: "homely-pets-packaging-mailer.png",
    desc: "Ridged edible chew with enzymes for daily dental care.",
  },
  {
    id: "dog-chew-kong",
    name: "Stuffable Heavy-Duty Chew Cone",
    pet: "dog",
    segment: "chews",
    type: "Chew toy",
    size: "Large",
    price: 15.9,
    img: "homely-pets-packaging-gift-box.png",
    desc: "Fill with snacks or purée for mental stimulation and slow chewing.",
  },

  /* ═══════════════════ CATS ═══════════════════ */

  /* —— Kitten food —— */
  {
    id: "cat-kitten-dry-turkey",
    name: "Kitten Dry — Turkey & Rice (1kg)",
    pet: "cat",
    segment: "kitten",
    type: "Dry food",
    size: "1kg",
    price: 14.9,
    img: "homely-pets-dry-food-bag.png",
    desc: "Extra protein and calcium for growth up to 12 months.",
  },
  {
    id: "cat-kitten-dry-chicken",
    name: "Kitten Dry — Chicken & Fish (1kg)",
    pet: "cat",
    segment: "kitten",
    type: "Dry food",
    size: "1kg",
    price: 15.5,
    img: "homely-pets-dry-food-bag.png",
    desc: "DHA-enriched kibble for brain and vision development.",
  },
  {
    id: "cat-kitten-wet-pate",
    name: "Kitten Wet — Turkey & Liver Paté (10 pack)",
    pet: "cat",
    segment: "kitten",
    type: "Wet food",
    size: "10 × 85g",
    price: 14.5,
    img: "homely-pets-wet-food-packaging.png",
    desc: "Silky paté with extra calories for fast-growing kittens.",
  },
  {
    id: "cat-kitten-wet-chicken",
    name: "Kitten Wet — Chicken Broth Shreds (12 pack)",
    pet: "cat",
    segment: "kitten",
    type: "Wet food",
    size: "12 × 85g",
    price: 15.9,
    img: "homely-pets-wet-food-packaging.png",
    desc: "Hydrating shreds for kittens learning to eat wet food.",
  },

  /* —— Adult cat food —— */
  {
    id: "cat-adult-dry-fish",
    name: "Adult Dry — Chicken & White Fish (1.5kg)",
    pet: "cat",
    segment: "adult",
    type: "Dry food",
    size: "1.5kg",
    price: 19.9,
    badge: "Bestseller",
    img: "homely-pets-dry-food-bag.png",
    desc: "High protein, taurine-fortified crunchy kibble for dental health.",
  },
  {
    id: "cat-adult-dry-indoor",
    name: "Adult Dry — Indoor Hairball Care (1.5kg)",
    pet: "cat",
    segment: "adult",
    type: "Dry food",
    size: "1.5kg",
    price: 21.5,
    img: "homely-pets-dry-food-bag.png",
    desc: "Fibre blend to reduce hairballs. Lower calorie for indoor cats.",
  },
  {
    id: "cat-adult-dry-salmon",
    name: "Adult Dry — Salmon & Sweet Potato (1.5kg)",
    pet: "cat",
    segment: "adult",
    type: "Dry food",
    size: "1.5kg",
    price: 20.9,
    img: "homely-pets-dry-food-bag.png",
    desc: "Omega-rich salmon for coat shine and skin comfort.",
  },
  {
    id: "cat-adult-dry-urinary",
    name: "Adult Dry — Urinary Care Chicken & Cranberry (1.5kg)",
    pet: "cat",
    segment: "adult",
    type: "Dry food",
    size: "1.5kg",
    price: 23.9,
    img: "homely-pets-dry-food-bag.png",
    desc: "Controlled minerals and cranberry for urinary tract support.",
  },
  {
    id: "cat-adult-wet-tuna",
    name: "Adult Wet — Tuna & Sole (12 pack)",
    pet: "cat",
    segment: "adult",
    type: "Wet food",
    size: "12 × 85g",
    price: 16.9,
    img: "homely-pets-wet-food-packaging.png",
    desc: "Seafood in silky gravy. 100% complete for adult cats.",
  },
  {
    id: "cat-adult-wet-chicken",
    name: "Adult Wet — Chicken Broth Pouches (12 pack)",
    pet: "cat",
    segment: "adult",
    type: "Wet food",
    size: "12 × 85g",
    price: 15.5,
    img: "homely-pets-wet-food-packaging.png",
    desc: "Hydration boost for cats that drink little water.",
  },
  {
    id: "cat-adult-wet-duck",
    name: "Adult Wet — Duck & Green Bean (12 pack)",
    pet: "cat",
    segment: "adult",
    type: "Wet food",
    size: "12 × 85g",
    price: 17.9,
    img: "homely-pets-wet-food-packaging.png",
    desc: "Novel protein for cats with common poultry sensitivities.",
  },
  {
    id: "cat-adult-wet-multipack",
    name: "Adult Wet — Variety Multipack (24 pack)",
    pet: "cat",
    segment: "adult",
    type: "Wet food",
    size: "24 × 85g",
    price: 28.9,
    badge: "Value size",
    img: "homely-pets-wet-food-packaging.png",
    desc: "Chicken, tuna, and duck rotation box for fussy adult cats.",
  },

  /* —— Senior cat food —— */
  {
    id: "cat-senior-dry-care",
    name: "Senior Dry — Chicken & Joint Care (1.5kg)",
    pet: "cat",
    segment: "senior",
    type: "Dry food",
    size: "1.5kg",
    price: 22.5,
    img: "homely-pets-dry-food-bag.png",
    desc: "Lower phosphorus and added glucosamine for cats 7+ years.",
  },
  {
    id: "cat-senior-wet-salmon",
    name: "Senior Wet — Turkey & Salmon (12 pack)",
    pet: "cat",
    segment: "senior",
    type: "Wet food",
    size: "12 × 85g",
    price: 17.5,
    badge: "Senior",
    img: "homely-pets-wet-food-packaging.png",
    desc: "Kidney-gentle with taurine and joint nutrients for mature cats.",
  },
  {
    id: "cat-senior-wet-pate",
    name: "Senior Wet — Soft Chicken Paté (12 pack)",
    pet: "cat",
    segment: "senior",
    type: "Wet food",
    size: "12 × 85g",
    price: 16.9,
    img: "homely-pets-wet-food-packaging.png",
    desc: "Ultra-soft texture for seniors with fewer teeth.",
  },

  /* —— Cat snacks & treats —— */
  {
    id: "cat-snack-tuna",
    name: "Crunchy Treats — Tuna",
    pet: "cat",
    segment: "snacks",
    type: "Snacks",
    size: "60g",
    price: 4.9,
    img: "homely-pets-packaging-mailer.png",
    desc: "Air-dried bites. Under 2 kcal per treat.",
  },
  {
    id: "cat-snack-dental",
    name: "Dental Crunchies — Chicken",
    pet: "cat",
    segment: "snacks",
    type: "Snacks",
    size: "50g",
    price: 5.9,
    img: "homely-pets-packaging-mailer.png",
    desc: "Crunchy texture helps reduce tartar build-up.",
  },
  {
    id: "cat-snack-salmon",
    name: "Freeze-Dried Salmon Cubes",
    pet: "cat",
    segment: "snacks",
    type: "Snacks",
    size: "50g",
    price: 7.9,
    img: "homely-pets-packaging-mailer.png",
    desc: "Single-ingredient omega snack. Break into smaller pieces.",
  },
  {
    id: "cat-snack-lick",
    name: "Lickable Treat — Tuna & Anchovy (6 pack)",
    pet: "cat",
    segment: "snacks",
    type: "Snacks",
    size: "6 × 60g",
    price: 7.5,
    img: "homely-pets-wet-food-packaging.png",
    desc: "Squeeze tubes for lick mats and bonding time.",
  },
  {
    id: "cat-snack-bonito",
    name: "Bonito Flakes — Sprinkle Topper",
    pet: "cat",
    segment: "snacks",
    type: "Snacks",
    size: "30g",
    price: 6.9,
    img: "homely-pets-packaging-mailer.png",
    desc: "Umami-rich flakes to tempt picky eaters onto meals.",
  },
  {
    id: "cat-snack-kitten",
    name: "Kitten Soft Treats — Chicken & Milk",
    pet: "cat",
    segment: "snacks",
    type: "Snacks",
    size: "50g",
    price: 5.5,
    img: "homely-pets-packaging-mailer.png",
    desc: "Soft morsels sized for kittens under 12 months.",
  },

  /* —— Cat toys & enrichment —— */
  {
    id: "cat-toy-wand",
    name: "Feather Wand Teaser",
    pet: "cat",
    segment: "toys",
    type: "Toy",
    size: "Extendable",
    price: 9.9,
    img: "homely-pets-packaging-mailer.png",
    desc: "Replaceable feather head for daily hunting play.",
  },
  {
    id: "cat-toy-mice",
    name: "Catnip Mice — 2 Pack",
    pet: "cat",
    segment: "toys",
    type: "Toy",
    size: "2 toys",
    price: 7.5,
    img: "homely-pets-packaging-mailer.png",
    desc: "Organic catnip-filled mice with crinkle tails.",
  },
  {
    id: "cat-toy-scratch",
    name: "Cardboard Scratch Lounge",
    pet: "cat",
    segment: "toys",
    type: "Toy",
    size: "45 × 25cm",
    price: 18.9,
    img: "homely-pets-packaging-gift-box.png",
    desc: "Corrugated lounge scratcher with catnip sprinkle included.",
  },
  {
    id: "cat-toy-tunnel",
    name: "Collapsible Play Tunnel",
    pet: "cat",
    segment: "toys",
    type: "Toy",
    size: "90cm",
    price: 16.5,
    img: "homely-pets-packaging-gift-box.png",
    desc: "Crinkle tunnel for chase games and shy cat confidence building.",
  },
  {
    id: "cat-toy-ball-track",
    name: "Turntable Ball Track Toy",
    pet: "cat",
    segment: "toys",
    type: "Toy",
    size: "One size",
    price: 14.9,
    img: "homely-pets-packaging-mailer.png",
    desc: "Spinning balls on three levels for solo indoor enrichment.",
  },
  {
    id: "cat-toy-puzzle",
    name: "Puzzle Feeder — Slow Eat Maze",
    pet: "cat",
    segment: "toys",
    type: "Toy",
    size: "250ml",
    price: 13.9,
    img: "homely-pets-packaging-mailer.png",
    desc: "Slows eating and adds mental stimulation at mealtimes.",
  },
];

/** Shop page sections: Dogs and Cats with life-stage / type subheadings */
window.HOMELY_CATALOG_LAYOUT = [
  {
    id: "dogs",
    title: "Dogs",
    pet: "dog",
    groups: [
      { segment: "puppy", title: "Puppy food" },
      { segment: "adult", title: "Adult food" },
      { segment: "senior", title: "Senior food" },
      { segment: "competition", title: "Competition & bulking food" },
      { segment: "snacks", title: "Snacks & treats" },
      { segment: "chews", title: "Chew toys" },
    ],
  },
  {
    id: "cats",
    title: "Cats",
    pet: "cat",
    groups: [
      { segment: "kitten", title: "Kitten food" },
      { segment: "adult", title: "Adult food" },
      { segment: "senior", title: "Senior food" },
      { segment: "snacks", title: "Snacks & treats" },
      { segment: "toys", title: "Toys & enrichment" },
    ],
  },
];

window.HOMELY_CATEGORIES = [
  { id: "all", label: "All products" },
  { id: "dogs", label: "Dogs" },
  { id: "cats", label: "Cats" },
  { id: "dog-puppy", label: "Dog · Puppy" },
  { id: "dog-adult", label: "Dog · Adult" },
  { id: "dog-senior", label: "Dog · Senior" },
  { id: "dog-competition", label: "Dog · Competition" },
  { id: "dog-snacks", label: "Dog · Snacks" },
  { id: "dog-chews", label: "Dog · Chews" },
  { id: "cat-kitten", label: "Cat · Kitten" },
  { id: "cat-adult", label: "Cat · Adult" },
  { id: "cat-senior", label: "Cat · Senior" },
  { id: "cat-snacks", label: "Cat · Snacks" },
  { id: "cat-toys", label: "Cat · Toys" },
];
